tap "derailed/k9s"
tap "go-task/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "lusingander/tap"
tap "microsoft/mssql-release"
tap "nikitabobko/tap"
tap "noahgorstein/tap"
brew "xz"
brew "ca-certificates"
brew "pycparser"
brew "cffi"
brew "cryptography"
brew "sqlite"
brew "awscli"
brew "bash"
brew "libssh2"
brew "libgit2"
brew "bat"
brew "berkeley-db"
brew "btop"
brew "c-ares"
brew "glib"
brew "harfbuzz"
brew "chafa"
brew "crunch"
brew "csvkit"
brew "direnv"
brew "docutils"
brew "eza"
brew "fd"
brew "fzf"
brew "gcc"
brew "gdbm"
brew "gh"
brew "ghorg"
brew "git"
brew "git-delta"
brew "gnu-getopt"
brew "gnu-sed"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "go"
brew "helm"
brew "htop"
brew "httpie"
brew "iperf3"
brew "jq"
brew "kcat"
brew "kubernetes-cli"
brew "lazydocker"
brew "lazygit"
brew "libiconv"
brew "libpq"
brew "luajit"
brew "luarocks"
brew "make"
brew "mas"
brew "mkcert"
brew "tree-sitter"
brew "neovim"
brew "netcat"
brew "nmap"
brew "node"
brew "p7zip"
brew "pass"
brew "pkgconf"
brew "prettier"
brew "python-setuptools"
brew "python@3.11"
brew "python-tk@3.11"
brew "python@3.9"
brew "ripgrep"
brew "rsync"
brew "s3cmd"
brew "showkey"
brew "speedtest-cli"
brew "sqlfluff"
brew "sshs"
brew "starship"
brew "stow"
brew "telnet"
brew "tfenv"
brew "tmux"
brew "unzip"
brew "watch"
brew "wget"
brew "whois"
brew "xh"
brew "yazi"
brew "youtube-dl"
brew "yq"
brew "zellij"
brew "zip"
brew "zoxide"
brew "derailed/k9s/k9s"
brew "go-task/tap/go-task"
brew "lusingander/tap/stu"
brew "noahgorstein/tap/jqp"
cask "1password-cli"
cask "adobe-acrobat-reader"
cask "aerospace"
cask "alt-tab"
cask "brave-browser"
cask "clickhouse"
cask "cursor"
cask "deepl"
cask "devtoys"
cask "docker"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
cask "iterm2"
cask "obsidian"
cask "postman"
cask "shadowsocksx-ng"
cask "warp"
cask "wezterm"
cask "zen-browser"
mas "1Password for Safari", id: 1569813296
mas "AdGuard for Safari", id: 1440147259
mas "Bitwarden", id: 1352778147
mas "Cubox", id: 1113361350
mas "Cubox for Safari", id: 1550721541
mas "Dark Night", id: 1592844577
mas "Fantastical", id: 975937182
mas "Gestimer", id: 6447125648
mas "Hidden Bar", id: 1452453066
mas "Highlights", id: 1498912833
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Noir", id: 1592917505
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Save to Raindrop.io", id: 1549370672
mas "superagent", id: 1568262835
mas "Telegram", id: 747648890
mas "Toggl Track", id: 1291898086
mas "Translatium", id: 6541750489
mas "Windows App", id: 1295203466
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
vscode "aaron-bond.better-comments"
vscode "arcticicestudio.nord-visual-studio-code"
vscode "britesnow.vscode-toggle-quotes"
vscode "catppuccin.catppuccin-vsc"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "charliermarsh.ruff"
vscode "christian-kohler.path-intellisense"
vscode "ciiqr.paste-indented"
vscode "dorzey.vscode-sqlfluff"
vscode "dotenv.dotenv-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "huytd.nord-light"
vscode "kevinrose.vsc-python-indent"
vscode "mads-hartmann.bash-ide-vscode"
vscode "miguelsolorio.fluent-icons"
vscode "mquandalle.graphql"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "njpwerner.autodocstring"
vscode "njqdev.vscode-python-typehint"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "shakram02.bash-beautify"
vscode "tamasfe.even-better-toml"
vscode "teabyii.ayu"
vscode "usernamehw.errorlens"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscodevim.vim"
vscode "yzhang.markdown-all-in-one"
