# Repo: https://github.com/alacritty/alacritty
# Dosc about configuration: https://alacritty.org/config-alacritty.html
#
[general]
# Setup theme.
# All available themes can be downloaded from here:
# https://github.com/alacritty/alacritty-theme
# import = ["~/.config/alacritty/themes/catppuccin_latte.toml"]
import = ["~/.config/alacritty/themes/catppuccin_frappe.toml"]

[env]
TERM = "xterm-256color"

[window]
# Use only predictable spacing
dynamic_padding = false
padding = { x = 7, y = 7 }

decorations = "Buttonless"

opacity = 0.95
blur = true

startup_mode = "Windowed"

[font]
size = 14
builtin_box_drawing = false

normal = { family = "JetBrainsMonoNL Nerd Font Propo", style = "ExtraLight" }
italic = { family = "JetBrainsMonoNL Nerd Font Propo", style = "ExtraLight Italic" }
bold = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Medium" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Medium Italic" }

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Beam", blinking = "Off" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

[[hints.enabled]]
# Enable to underline links inside alacritty.
# To underline press `shift`, to go to that link press `shift` and then left mouse key.
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse = { enabled = true }
binding = { key = "Shift", mods = "Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
