#!/usr/bin/env zsh
# vim: set filetype=sh:
# vim: set ts=4 sw=4 et:

# https://github.com/sharkdp/bat
if command -v bat &>/dev/null; then

    # Set zsh-syntax-highlighting theme
    export BAT_THEME="catppuccin-frappe"
    # Setup output elements to show
    export BAT_STYLE="header,numbers,grid"
    export BAT_PAGING="always"
    export BAT_PAGER="less -RF"

    # Use bat to show man pages output.
    # https://github.com/sharkdp/bat#man
    export MANPAGER="sh -c 'col -bx | bat --language=man --style=plain'"

    # Use bat to show help pages output.
    # https://github.com/sharkdp/bat?tab=readme-ov-file#highlighting---help-messages
    alias -g -- -h='-h 2>&1 | bat --language=help --style=plain'
    alias -g -- --help='--help 2>&1 | bat --language=help --style=plain'
fi

# ========= fzf =========
# https://github.com/junegunn/fzf
if command -v fzf &>/dev/null; then
    # Set up fzf key bindings and fuzzy completion
    # https://github.com/junegunn/fzf?tab=readme-ov-file#setting-up-shell-integration
    source <(fzf --zsh)

    # https://github.com/junegunn/fzf#layout
    # export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border=sharp --margin=0,1,0,1%"

    # Options to fzf command
    # export FZF_COMPLETION_OPTS='--border --info=inline'

    # Catppuccin frappe theme.
    # https://github.com/catppuccin/fzf
    export FZF_DEFAULT_OPTS=" \
        --color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf \
        --color=marker:#babbf1,fg+:#c6d0f5,prompt:#ca9ee6,hl+:#e78284 \
        --color=selected-bg:#51576d \
        --multi"

    export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

    # Use fd (https://github.com/sharkdp/fd) for listing path candidates.
    # - The first argument to the function ($1) is the base path to start traversal
    # - See the source code (completion.{bash,zsh}) for the details.
    _fzf_compgen_path() {
        fd --hidden --exclude .git . "$1"
    }

    # Use fd to generate the list for directory completion
    _fzf_compgen_dir() {
        fd --type=d --hidden --exclude .git . "$1"
    }

    show_file_or_dir_preview="if [ -d {} ]; then eza --tree --color=always {} | head -200; else bat -n --color=always --line-range :500 {}; fi"

    export FZF_CTRL_T_OPTS="--preview '$show_file_or_dir_preview'"
    export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

    function _fzf_comprun() {
        local command=$1
        shift

        case "$command" in
        cd) fzf --preview 'tree -C {} | head -200' "$@" ;;
        export | unset) fzf --preview "eval 'echo \$'{}" "$@" ;;
        ssh) fzf --preview 'dig {}' "$@" ;;
        *) fzf --preview "$show_file_or_dir_preview" "$@" ;;
        esac
    }
fi

# ========== starship ==========
if command -v starship &>/dev/null; then
    eval "$(starship init zsh)"
    # Set var with path to config file
    export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
fi

# ========= yazi =========
# Use `yy` as shell command wrapper that provides the ability
# to change the current working directory when exiting Yazi.
# Took from utility doc: https://yazi-rs.github.io/docs/quick-start#shell-wrapper
if command -v yazi &>/dev/null; then
    function yy() {
        local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
        yazi "$@" --cwd-file="$tmp"
        if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
            cd -- "$cwd"
        fi
        rm -f -- "$tmp"
    }
fi

# ========= zoxide =========
if command -v zoxide &>/dev/null; then
    eval "$(zoxide init zsh)"
    alias cd="z"
fi

# ========== direnv ==========
if command -v direnv &>/dev/null; then
    eval "$(direnv hook zsh)"
fi

# https://github.com/noahgorstein/jqp?tab=readme-ov-file#configuration
if command -v jqp &>/dev/null; then
    alias jqp="jqp --theme catppuccin-frappe"
fi
