#!/usr/bin/env zsh
# vim: set filetype=sh:
# vim: set ts=4 sw=4 et:



if command -v uv &>/dev/null; then
    eval "$(uv generate-shell-completion zsh)"
fi

if [[ -d "$HOME/.cargo" ]];
    then source "$HOME/.cargo/env"
fi
