#!/usr/bin/env zsh
# vim: set filetype=sh:
# vim: set ts=4 sw=4 et:

zj="zellij"

# ========= homebrew =========
if command -v /opt/homebrew/bin/brew &>/dev/null; then
    # Export all `brew` env vars. See `man brew` + `/shellenv`
    eval "$(/opt/homebrew/bin/brew shellenv)"

    # No emoji in download output
    # export HOMEBREW_NO_EMOJI=1
    export HOMEBREW_INSTALL_BADGE=""

    # Don't show hints for env vatialbes
    export HOMEBREW_NO_ENV_HINTS=1
    export HOMEBREW_NO_AUTO_UPDATE=1

    export HOMEBREW_CACHE="$XDG_CACHE_HOME/homebrew"

    # Add to FPATH completions installed by brew
    FPATH="/opt/homebrew/share/zsh/site-functions:$FPATH"
fi

# Yank in vi mode to the system clipboard
function vi-yank-xclip {
    zle vi-yank
    echo "$CUTBUFFER" | pbcopy -i
}
zle -N vi-yank-xclip
bindkey -M vicmd 'y' vi-yank-xclip

# ========== 1password cli ==========
if command -v op &>/dev/null; then
    eval "$(op completion zsh)"
fi

# Yandex Cloud CLI - `yc`.
# Add binary to PATH.
if [ -d "$HOME/.yandex-cloud/bin" ]; then
    export PATH="$HOME/.yandex-cloud/bin:${PATH}"

    # Enable zsh completions.
    if [ -f "$HOME/.yandex-cloud/completion.zsh.inc" ]; then
        source "$HOME/.yandex-cloud/completion.zsh.inc"
    fi

    # Add aliases for some common commands.
    alias yccil="yc compute instance list"
fi

if command -v stu &>/dev/null; then
    alias smlts3="stu \
        --endpoint-url https://minio.prod.lh.samoletgroup.ru:9000 \
        --profile smlt-bdd-minio \
        --bucket data \
        --region us-east-1
    "
fi
