---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  ip:get-info:
    desc: Show full json returned by ifconfig.me
    cmd: curl -s ifconfig.me/all.json | jq {{ .CLI_ARGS }}

  ip:get:
    desc: Show only my IP
    cmd: curl -s ifconfig.me/ip

  ping:
    desc: Ping google.com
    cmd: ping -c 10 google.com
