---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  bat-cache-build:
    desc: Build or rebuild bat cache
    cmd: bat cache --build

  generate-extra-completions:
    desc: Generate usefull completions
    vars:
      COMPLETIONS_DIR:
        sh: echo "$XDG_DATA_HOME/zsh/site-functions"
    cmds:
      - if [[ ! -d {{.COMPLETIONS_DIR}} ]]; then mkdir -p {{.COMPLETIONS_DIR}}; fi
      - uv generate-shell-completion zsh >! {{.COMPLETIONS_DIR}}/_uv
      - op completion zsh >! {{.COMPLETIONS_DIR}}/_op
      - kaf completion zsh >! {{.COMPLETIONS_DIR}}/_kaf
      - opencode completion >! {{.COMPLETIONS_DIR}}/_opencode

  install-submodules:
    desc: Install all git submodules
    cmd: git submodule update --init --recursive

  stow-essential:
    desc: Run stow with essential entities
    cmds:
      - cmd: stow stow
      - cmd: cat ./stow/darwin-essential | xargs -I {} stow {}
        platforms: [darwin]
      - cmd: cat ./stow/linux-essential | xargs -I {} stow {}
        platforms: [linux]

  atuin-sync:
    desc: Sync local atuin history with the server
    cmd: atuin sync

