# The common config file for `ruff`.
# All available settings:
cache-dir = "~/.cache/ruff"

# The number of spaces per indentation level (tab).
indent-width = 4

# The length is determined by the number of characters per line.
line-length = 100 # Allow lines to be as long as 100

[lint]
# https://docs.astral.sh/ruff/settings/#lint_select
# All  available rules: https://docs.astral.sh/ruff/rules/#rules
select = [
    # Category: pycodestyle
    # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "E", # All erorrs
    "W", # All warnigns
    # Category: PyFlake
    # https://docs.astral.sh/ruff/rules/#pyflakes-f
    "F", # All rules
    # Category: isort
    "I", # All rules
    # Category: Ruff-specific rules
    "RUF",
    # Category: Airflow
    "AIR",
    # Category: Pandas
    # https://docs.astral.sh/ruff/rules/#pandas-vet-pd
    "PD",

]

# https://docs.astral.sh/ruff/settings/#lint_ignore
ignore = ["RUF001", "RUF002", "RUF003", "PD901", "PD010", "E501", "F821", "F841", "F401"]

[lint.pydocstyle]
convention = "google"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# https://docs.astral.sh/ruff/settings/#format_indent-style
indent-style = "space"

# https://docs.astral.sh/ruff/settings/#format_skip-magic-trailing-comma
skip-magic-trailing-comma = false

# https://docs.astral.sh/ruff/settings/#format_line-ending
line-ending = "lf" # Use `\n` line endings for all files.

# Enable reformatting of code snippets in docstrings.
# https://docs.astral.sh/ruff/settings/#format_docstring-code-format
docstring-code-format = true

# https://docs.astral.sh/ruff/settings/#format_docstring-code-line-length
docstring-code-line-length = "dynamic"
