#!/usr/bin/env zsh
# vim: set filetype=sh:
# vim: set ts=4 sw=4 et:

# Bacis
alias rm="rm -Iv"
alias cp="cp -iv"
alias mv="mv -iv"
alias h="history | tail -n 50"
alias c="clear"

# Aliases for particular tools
alias k="kubectl"
alias d="docker"
alias t="terraform"

alias gr="rg --color=always"

alias ls="eza --all --oneline --icons --group-directories-first"
alias ll="eza --all --long --icons --group-directories-first --created --modified --header --binary --time-style long-iso"
alias tree="eza --tree --all --icons --group-directories-first --ignore-glob='.git*|.venv*|__pycache__*|.DS_store'"
