#!/usr/bin/env zsh
# vim: set filetype=sh:
# vim: set ts=4 sw=4 et:

# === Zellij ===
alias zj="zellij"

# === Homebrew ===
# Export all `brew` env vars. See `man brew` + `/shellenv`
eval "$(/opt/homebrew/bin/brew shellenv)"

export HOMEBREW_INSTALL_BADGE=""
export HOMEBREW_NO_ENV_HINTS=1 # Don't show hints for env vatialbes
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ANALYTICS=1  # disables statistics that brew collects

export HOMEBREW_CACHE="$XDG_CACHE_HOME/homebrew"

# Add to FPATH completions installed by brew
FPATH="/opt/homebrew/share/zsh/site-functions:$FPATH"

# === vi-mode ====
# Yank in vi mode to the system clipboard
function vi-yank-xclip {
    zle vi-yank
    echo "$CUTBUFFER" | pbcopy -i
}
zle -N vi-yank-xclip
bindkey -M vicmd 'y' vi-yank-xclip

# === 1password CLI ===
eval "$(op completion zsh)"

# === Yandex Cloud CLI ===
export PATH="$HOME/.yandex-cloud/bin:${PATH}"
# Enable zsh completions.
if [ -f "$HOME/.yandex-cloud/completion.zsh.inc" ]; then
    source "$HOME/.yandex-cloud/completion.zsh.inc"
fi

# STU
alias smlts3="stu \
    --endpoint-url https://minio.prod.lh.samoletgroup.ru:9000 \
    --profile smlt-bdd-minio \
    --bucket data \
    --region us-east-1
"
