#!/usr/bin/env zsh
# vim: set filetype=sh:
# vim: set ts=4 sw=4 et:

# === direnv ===
eval "$(direnv hook zsh)"

# === jqp ===
# https://github.com/noahgorstein/jqp?tab=readme-ov-file#configuration
alias jqp="jqp --theme catppuccin-frappe"


# === docker ===
export DOCKER_CLI_HINTS=false  # disable ads in CLI
