# Doc: https://yazi-rs.github.io/docs/configuration/yazi
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[opener]
edit = [{ run = '$EDITOR "$@"', desc = "$EDITOR", block = true, for = "unix" }]

[mgr]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "none"
show_hidden = true
show_symlink = true
scrolloff = 5

[preview]
tab_size = 4

[input]
find_title = ["Find next:", "Find previous:"]
find_origin = "center"
find_offset = [0, 2, 50, 3]

rename_title  = "Rename:"
rename_origin = "center"
rename_offset = [ 0, 1, 50, 3 ]

create_title = ["Create:", "Create (dir):"]
create_origin = "center"
create_offset = [0, 1, 50, 3]
