# All config options described here: https://docs.atuin.sh/configuration/config

# If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
enter_accept = false

keymap_mode = "vim-insert"

style = 'compact'
invert = true

history_filter = [
    "^cd",
    "^(nvim|vim|vi|v)?\\s*\\.?\\s*$",
    "^ls\\s*-*(l|a|la|al)?\\s*\\.?\\s*$",
    "^(z|zoxide)\\s*.*$",
    "^.+\\s(-h|--help)\\s*$"
]

[theme]
name = "catppuccin-frappe-lavender"
