#!/usr/bin/env sh
#YABAI STUFF

# Configuration file for `yabai` utitily

# Default layout to use. Can be `bsp`, `stack` or `float`)
# `bsp` - Managed by `yabai`
# `stack` - ?
# `float` - Regular float window without`yabai` autoresize
yabai -m config layout float

# Balance the window tree upon change, so that all windows occupy the same area.
# on or off (default: off)
yabai -m config auto_balance off

# When focusing a window, put the mouse at its center.
yabai -m config mouse_follows_focus on

# Disable default apple app shadow on window frame 
yabai -m config window_shadow off

# Action performed when a bsp-managed window is dropped in the center
# of some other bsp-managed window.
# yabai -m config mouse_drop_action stack

# Set all padding and gaps to 20pt (default: 0).
# Works only if windows managed by `yabai`. 
# yabai -m config top_padding 12
# yabai -m config bottom_padding 12
# yabai -m config left_padding 12
# yabai -m config right_padding 12

# WINDOW MOVEMENT
#
# Set modifier-key for clicking and dragging with mouse.
# Can be one of: `cmd`, `alt`, `shift`, `ctri` or `fn`
yabai -m config mouse_modifier fn

# Set modifier-key + left-click drag = move window
yabai -m config mouse_action1 move

# Set modifier-key + right-click drag = resize window
yabai -m config mouse_action2 resize

# SIGNALS
#
# To see all created signals: `yabai -m signal --list | jq`

# Create signals for apps to resize when window was created.
apps=(Obsidian Code iTerm2 Safari) # Target apps

for app in "${apps[@]}"; do  
    "$i"
    yabai -m signal --add \
        event=window_created \
        app="^$app$" \
        action="bash /Users/leonidgrisenkov/Code/configs/yabai/.config/yabai/resize-app.sh $app"

done

# END

